// <auto-generated />
namespace DDAC_Website.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newonw : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newonw));
        
        string IMigrationMetadata.Id
        {
            get { return "201612181550315_newonw"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
